### PR TITLE
Add UtilitiX

### PR DESCRIPTION
**Pull request by MelanX**
I made a seperate folder just for "melanx" because I wanted to add other mods, too. I don't know if I still want to add them during this month, so I keep it up to you if I should remove this sub-folder or not.

### CODE REVIEW

**Comment by Trikzon** [comment]
I don't think there is really a clear folder structure defined anywhere. Personally for my PRs adding support to mods, I made a subfolder for each author, so I think having a `melanx` folder even with just one mod is fine.

**Review by AbsolemJackdaw — COMMENTED** [review]
Is the provided texture a 256x256 image with the texture in it, like a screen texture normally is in vanilla, or is it completely filling up the image space ? if that's the case, you need to give the image size too, because the default is a piece of texture in a 256x256 image. 
The texSize should also be used in the latter case

**Comment by Trikzon** [comment]
Should the textures be 256x256? My 2nd PR used 255x255 images (which I thought was strange) because you wiki says to make them 255x255.

**Comment by AbsolemJackdaw** [comment]
doesnt really matter. one pixel difference wont stretch them too much. i think my editing software starts at 1 insead of 0 so it shows 255x textures instead of 256 lol

**Comment by Trikzon** [comment]
Fair enough. I might make another PR in a few days for support for a few more mods, so I'll fix them to 256x256 anyways in that if I do.

**Comment by MelanX** [comment]
It’s just the texture, not 256x256, and I provided the "texSize" for that image. Or did I another thing wrong?

**Comment by AbsolemJackdaw** [comment]
on second review everything is indeed done correctly. must have looked at it cross eyed two days ago ...

**Pull request merged**
